[profile.default]
solc_version = "0.8.17"
libs = ['node_modules','lib']

cache_path = 'forge-cache'

[fuzz]
runs = 10_000
max_test_rejects = 200_000

[profile.lsp-smart-contracts]
src = 'packages/lsp-smart-contracts/contracts'
test = 'packages/lsp-smart-contracts/foundry'
out = 'packages/lsp-smart-contracts/out'
gas_reports = ["LSP6ExecuteRestrictedController", "LSP6ExecuteUnrestrictedController", "LSP6SetDataRestrictedController", "LSP6SetDataUnrestrictedController"]

[profile.lsp2]
src = 'packages/LSP2ERC725YJSONSchema/contracts'
test = 'packages/LSP2ERC725YJSONSchema/foundry'
out = 'packages/LSP2ERC725YJSONSchema/contracts/foundry_artifacts'

[profile.lsp6]
src = 'packages/LSP6KeyManager/contracts'
test = 'packages/LSP6KeyManager/foundry'
out = 'packages/LSP6KeyManager/contracts/foundry_artifacts'

[profile.lsp16]
src = 'packages/LSP16UniversalFactory/contracts'
test = 'packages/LSP16UniversalFactory/foundry'
out = 'packages/LSP16UniversalFactory/contracts/foundry_artifacts'
